const $ = (s) => document.querySelector(s);
const $$ = (s) => [...document.querySelectorAll(s)];
const state = { asset: 'BTC', timeframe: '15m', projection: true, theme: 'dark', currentPrice: 64872.4, strategy:'intraday', order:{active:false,entry:0,target:0,fees:.003,approachAlerted:false,targetAlerted:false} };
const strategies={scalping:{label:'Scalping conservador',entry:'5m',confirm:'15m',trend:'1h',score:74,target:.8,risk:.8,exposure:'Reduzido'},intraday:{label:'Intraday',entry:'15m',confirm:'1h',trend:'4h',score:70,target:2,risk:1.5,exposure:'Moderado'},swing:{label:'Swing trade',entry:'4h',confirm:'1D',trend:'1S',score:68,target:4,risk:2.5,exposure:'Ampliado'}};
const timeframeConfigs={
  '5m':{seed:5,vol:.0038,trend:.00024,labels:['10:00','11:00','12:00','13:00','14:00','15:00','16:00']},
  '15m':{seed:15,vol:.0058,trend:.00042,labels:['10:00','12:00','14:00','16:00','18:00','20:00','22:00']},
  '1h':{seed:60,vol:.0074,trend:.00058,labels:['03:00','06:00','09:00','12:00','15:00','18:00','21:00']},
  '4h':{seed:240,vol:.0096,trend:.00072,labels:['seg','ter','qua','qui','sex','sáb','dom']},
  '1D':{seed:1440,vol:.0125,trend:.00088,labels:['02 jul','06 jul','10 jul','14 jul','18 jul','22 jul','26 jul']},
  '1S':{seed:10080,vol:.016,trend:.00105,labels:['fev','mar','abr','mai','jun','jul','ago']}
};
const assets = [
  {symbol:'BTC',name:'Bitcoin',price:64872.40,change:'+1,82%',icon:'₿',color:'#f2a900'},
  {symbol:'ETH',name:'Ethereum',price:3448.18,change:'+2,41%',icon:'◆',color:'#667fea'},
  {symbol:'SOL',name:'Solana',price:158.72,change:'+4,12%',icon:'S',color:'#8b5cf6'},
  {symbol:'BNB',name:'BNB',price:587.31,change:'+0,74%',icon:'B',color:'#f3ba2f'}
];
const fmt = (n, digits=2) => '$' + n.toLocaleString('pt-BR',{minimumFractionDigits:digits,maximumFractionDigits:digits});
const seeded = (i) => { const x = Math.sin(i * 9283.17 + 74.3) * 43758.5; return x - Math.floor(x); };

function createCandles(base=62500, count=92){
  const config=timeframeConfigs[state.timeframe]||timeframeConfigs['15m'];let p=base; const list=[];
  for(let i=0;i<count;i++){
    const phase=i<20?.8:i<39?-.5:i<66?1.15:.4;
    const drift=config.trend*phase;
    const change=(seeded(i+config.seed)-.48)*config.vol+Math.sin((i+config.seed)*.23)*config.vol*.18+drift;
    const open=p; const close=open*(1+change); const wick=(.0015+seeded(i+200)*.004)*open;
    list.push({open,close,high:Math.max(open,close)+wick*(1+config.vol*35),low:Math.min(open,close)-wick*.8*(1+config.vol*30),volume:38+seeded(i+400+config.seed)*85+(i>64?22:0)}); p=close;
  }
  const scale=state.currentPrice/list.at(-1).close;
  return list.map(c=>({open:c.open*scale,close:c.close*scale,high:c.high*scale,low:c.low*scale,volume:c.volume}));
}
let candles=createCandles();
function ema(data, period){ const k=2/(period+1); let prev=data[0].close; return data.map((d,i)=>{prev=i?d.close*k+prev*(1-k):prev;return prev;}); }
function findProfitableEntries(data){const hits=[];for(let i=8;i<data.length-12;i++){if(hits.length&&i-hits.at(-1).entry<=9)continue;for(let horizon=1;horizon<=11;horizon++){const exit=i+horizon,gain=(data[exit].close/data[i].close-1)*100;if(gain>=.4&&gain<1){hits.push({entry:i,exit,gain});break}}}return hits.slice(-4)}
function drawChart(){
  const canvas=$('#priceChart'), wrap=$('#chartWrap'), dpr=Math.min(devicePixelRatio||1,2); const w=wrap.clientWidth,h=wrap.clientHeight;
  canvas.width=w*dpr; canvas.height=h*dpr; const ctx=canvas.getContext('2d'); ctx.scale(dpr,dpr); ctx.clearRect(0,0,w,h);
  const dark=!document.body.classList.contains('light'); const grid=dark?'#172722':'#e7eeeb', label=dark?'#60756e':'#81928c';
  const pad={l:10,r:61,t:14,b:34}, volH=65, plotH=h-pad.t-pad.b; const visible=candles; const forecastN=18;
  let lows=visible.map(c=>c.low), highs=visible.map(c=>c.high); const min=Math.min(...lows)*.997,max=Math.max(...highs)*1.003; const candleAreaW=(w-pad.l-pad.r)*.79; const step=candleAreaW/visible.length;
  const x=i=>pad.l+(i+.5)*step, y=v=>pad.t+(max-v)/(max-min)*(plotH-volH);
  ctx.font='8px DM Mono'; ctx.fillStyle=label; ctx.textAlign='left';
  for(let i=0;i<6;i++){const yy=pad.t+i*(plotH-volH)/5;ctx.beginPath();ctx.strokeStyle=grid;ctx.setLineDash([2,4]);ctx.moveTo(pad.l,yy);ctx.lineTo(w-pad.r,yy);ctx.stroke();ctx.setLineDash([]);const val=max-i*(max-min)/5;ctx.fillText(fmt(val,0),w-pad.r+8,yy+3)}
  const timeLabels=(timeframeConfigs[state.timeframe]||timeframeConfigs['15m']).labels;wrap.dataset.axisLabels=timeLabels.join('|');for(let i=0;i<7;i++){const xx=pad.l+i*(w-pad.l-pad.r)/6;ctx.beginPath();ctx.strokeStyle=grid;ctx.moveTo(xx,pad.t);ctx.lineTo(xx,h-pad.b);ctx.stroke();ctx.fillText(timeLabels[i],Math.min(xx+2,w-87),h-12)}
  const maxVol=Math.max(...visible.map(c=>c.volume)); visible.forEach((c,i)=>{const xx=x(i),up=c.close>=c.open,col=up?'#4fc49a':'#e36b65';const vy=h-pad.b-(c.volume/maxVol)*volH*.65;ctx.globalAlpha=.18;ctx.fillStyle=col;ctx.fillRect(xx-step*.34,vy,step*.68,h-pad.b-vy);ctx.globalAlpha=1;ctx.strokeStyle=col;ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(xx,y(c.high));ctx.lineTo(xx,y(c.low));ctx.stroke();ctx.fillStyle=col;const top=y(Math.max(c.open,c.close)),bh=Math.max(1.2,Math.abs(y(c.open)-y(c.close)));ctx.fillRect(xx-step*.29,top,step*.58,bh)});
  const series=[{v:ema(visible,9),c:'#65d9ac',w:1.5},{v:ema(visible,21),c:'#e8bc69',w:1.15},{v:ema(visible,50),c:'#9678ef',w:1.15}];
  series.forEach(s=>{ctx.beginPath();ctx.strokeStyle=s.c;ctx.lineWidth=s.w;s.v.forEach((v,i)=>i?ctx.lineTo(x(i),y(v)):ctx.moveTo(x(i),y(v)));ctx.stroke()});
  $('#ema9Label').textContent=series[0].v.at(-1).toLocaleString('pt-BR',{maximumFractionDigits:0});$('#ema21Label').textContent=series[1].v.at(-1).toLocaleString('pt-BR',{maximumFractionDigits:0});$('#ema50Label').textContent=series[2].v.at(-1).toLocaleString('pt-BR',{maximumFractionDigits:0});const volumeSum=visible.reduce((a,c)=>a+c.volume,0),vwap=visible.reduce((a,c)=>a+c.close*c.volume,0)/volumeSum;$('#vwapLabel').textContent=vwap.toLocaleString('pt-BR',{maximumFractionDigits:0});
  const profitableEntries=findProfitableEntries(visible);wrap.dataset.markerCount=profitableEntries.length;wrap.dataset.markerGains=profitableEntries.map(h=>h.gain.toFixed(2)).join(',');wrap.dataset.timeframe=state.timeframe;wrap.dataset.seriesSignature=visible.slice(0,6).map(c=>c.close.toFixed(2)).join('|');profitableEntries.forEach(hit=>{const ex=x(hit.entry),ey=y(visible[hit.entry].low)-13;ctx.save();ctx.shadowColor='rgba(101,217,172,.65)';ctx.shadowBlur=9;ctx.fillStyle='#65d9ac';ctx.beginPath();ctx.moveTo(ex,ey-10);ctx.lineTo(ex-8,ey+4);ctx.lineTo(ex+8,ey+4);ctx.closePath();ctx.fill();ctx.restore();ctx.fillStyle=dark?'#173a30':'#d9f4e9';ctx.fillRect(ex-22,ey+7,44,14);ctx.fillStyle=dark?'#8cf0c8':'#106b4e';ctx.font='700 8px DM Mono';ctx.textAlign='center';ctx.fillText('+'+hit.gain.toFixed(2)+'%',ex,ey+17);const xx=x(hit.exit),xy=y(visible[hit.exit].high)+13;ctx.save();ctx.shadowColor='rgba(238,116,109,.55)';ctx.shadowBlur=8;ctx.fillStyle='#ee746d';ctx.beginPath();ctx.moveTo(xx,xy+10);ctx.lineTo(xx-8,xy-4);ctx.lineTo(xx+8,xy-4);ctx.closePath();ctx.fill();ctx.restore();ctx.fillStyle=dark?'#40201e':'#fae2e0';ctx.fillRect(xx-20,xy-23,40,13);ctx.fillStyle=dark?'#ff9a94':'#9b2f2a';ctx.font='700 7px DM Mono';ctx.fillText('SAÍDA',xx,xy-14);ctx.textAlign='left'});
  if(state.projection){const start=visible.at(-1).close,sx=x(visible.length-1),fw=(w-pad.r-sx),points=forecastN+1;const med=Array.from({length:points},(_,i)=>start*(1+.0184*(i/forecastN)+Math.sin(i*.7)*.0012));const band=(mult)=>med.map((v,i)=>v*(1+mult*Math.sqrt(i/forecastN)));
    const outerUp=band(.018),outerDn=band(-.018),innerUp=band(.009),innerDn=band(-.009);ctx.save();ctx.beginPath();ctx.rect(sx,0,w-sx,h);ctx.clip();const area=(up,dn,color)=>{ctx.beginPath();up.forEach((v,i)=>i?ctx.lineTo(sx+i*fw/forecastN,y(v)):ctx.moveTo(sx,y(v)));[...dn].reverse().forEach((v,j)=>ctx.lineTo(sx+(forecastN-j)*fw/forecastN,y(v)));ctx.closePath();ctx.fillStyle=color;ctx.fill()};area(outerUp,outerDn,dark?'rgba(101,217,172,.045)':'rgba(22,141,103,.06)');area(innerUp,innerDn,dark?'rgba(101,217,172,.10)':'rgba(22,141,103,.12)');ctx.beginPath();ctx.strokeStyle='#65d9ac';ctx.setLineDash([4,4]);ctx.lineWidth=1.2;med.forEach((v,i)=>i?ctx.lineTo(sx+i*fw/forecastN,y(v)):ctx.moveTo(sx,y(v)));ctx.stroke();ctx.restore();ctx.setLineDash([]);ctx.beginPath();ctx.strokeStyle=dark?'#315047':'#a9beb6';ctx.setLineDash([3,4]);ctx.moveTo(sx,pad.t);ctx.lineTo(sx,h-pad.b);ctx.stroke();ctx.setLineDash([])}
  const entry=state.currentPrice*.9904, target=entry*1.02306, stop=entry*.98635; const levels=[{v:target,c:'#65d9ac',t:'ALVO'},{v:entry,c:'#7e918b',t:'ENTRADA'},{v:stop,c:'#ee746d',t:'STOP'}];levels.forEach(l=>{ctx.beginPath();ctx.strokeStyle=l.c;ctx.globalAlpha=.52;ctx.setLineDash([5,5]);ctx.moveTo(pad.l,y(l.v));ctx.lineTo(w-pad.r,y(l.v));ctx.stroke();ctx.globalAlpha=1;ctx.setLineDash([]);ctx.fillStyle=l.c;ctx.fillRect(w-pad.r,y(l.v)-8,53,15);ctx.fillStyle=dark?'#07100f':'#fff';ctx.font='700 6px Manrope';ctx.fillText(l.t,w-pad.r+5,y(l.v)+2)});
  const cy=y(visible.at(-1).close),cx=x(visible.length-1);ctx.fillStyle='#65d9ac';ctx.beginPath();ctx.arc(cx,cy,2.5,0,Math.PI*2);ctx.fill();ctx.fillStyle='#65d9ac';ctx.fillRect(w-pad.r,cy-8,55,16);ctx.fillStyle='#07100f';ctx.font='600 7px DM Mono';ctx.fillText(fmt(visible.at(-1).close,0),w-pad.r+5,cy+2);const pulse=$('#currentPricePulse');pulse.style.left=cx+'px';pulse.style.top=cy+'px';
  canvas._map={x,y,step,min,max,pad,w,h};
}

function setupChartInteraction(){const canvas=$('#priceChart'),tip=$('#chartTooltip');canvas.addEventListener('mousemove',e=>{const m=canvas._map;if(!m)return;const rect=canvas.getBoundingClientRect(),mx=e.clientX-rect.left;const i=Math.max(0,Math.min(candles.length-1,Math.floor((mx-m.pad.l)/m.step)));const c=candles[i];tip.innerHTML=`<b style="color:${c.close>=c.open?'#65d9ac':'#ee746d'}">${state.asset} · ${state.timeframe}</b><br>O ${fmt(c.open)} &nbsp; H ${fmt(c.high)}<br>L ${fmt(c.low)} &nbsp; C ${fmt(c.close)}<br>Vol ${c.volume.toFixed(1)} mi`;tip.style.left=Math.min(mx+12,m.w-165)+'px';tip.style.top=Math.max(10,e.clientY-rect.top-52)+'px';tip.classList.add('show')});canvas.addEventListener('mouseleave',()=>tip.classList.remove('show'))}

function chooseAsset(symbol){const a=assets.find(x=>x.symbol===symbol);state.asset=symbol;state.currentPrice=a.price;$('#assetName').textContent=a.name;$('#assetSymbol').textContent=a.symbol+' / USDT';$('#coinLogo').textContent=a.icon;$('#coinLogo').style.background=a.color;$('#currentPrice').textContent=fmt(a.price);$('.price-change').textContent=a.change;const entry=a.price*.9904,stop=entry*.98635;$('#entryPrice').textContent=fmt(entry);$('#stopPrice').textContent=fmt(stop);candles=createCandles(a.price*.963);$('#searchResults').classList.remove('show');$('#assetSearch').value='';calcTarget();drawChart();}
function setupSearch(){const input=$('#assetSearch'),box=$('#searchResults');const render=q=>{const f=assets.filter(a=>(a.name+a.symbol).toLowerCase().includes(q.toLowerCase()));box.innerHTML=f.map(a=>`<div class="search-option" data-symbol="${a.symbol}"><strong>${a.icon} &nbsp;${a.name}</strong><span>${a.symbol}/USDT</span></div>`).join('')||'<div class="search-option"><span>Nenhum ativo encontrado</span></div>';box.classList.toggle('show',!!q);$$('.search-option[data-symbol]').forEach(el=>el.onclick=()=>chooseAsset(el.dataset.symbol))};input.addEventListener('input',e=>render(e.target.value));document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();input.focus()}});document.addEventListener('click',e=>{if(!e.target.closest('.search-wrap'))box.classList.remove('show')})}
function openTrade(){const d=$('#tradeModal');if(typeof d.showModal==='function')d.showModal()}
function calcTarget(){const entry=state.currentPrice*.9904,buy=+$('#buyFee').value/100,sell=+$('#sellFee').value/100,slip=+$('#slippage').value/100,target=+$('#profitTarget').value/100,invest=+$('#investment').value||0;const price=entry*(1+buy+slip)*(1+target)/(1-sell-slip);$('#modalTarget').textContent=fmt(price);$('#expectedProfit').textContent=fmt(invest*target);return price}
function showToast(title,text,kind='success'){const toast=$('#toast');toast.querySelector('span').textContent=kind==='exit'?'↘':'✓';toast.querySelector('strong').textContent=title;toast.querySelector('small').textContent=text;toast.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.classList.remove('show'),3000)}
function showGoalAlert(hit=false){const alert=$('#goalAlert');alert.classList.toggle('hit',hit);$('#goalAlertLabel').textContent=hit?'META ATINGIDA':'ALERTA DE PROXIMIDADE';$('#goalAlertTitle').textContent=hit?'Lucro líquido atingido':'Preço próximo ao alvo';$('#goalAlertText').textContent=hit?'A operação pode ser encerrada conforme o objetivo escolhido.':'Falta menos de 0,20% para o lucro definido na ordem.';const old=alert.querySelector(':scope>i'),timer=old.cloneNode();old.replaceWith(timer);alert.classList.add('show');clearTimeout(showGoalAlert.timer);showGoalAlert.timer=setTimeout(()=>alert.classList.remove('show'),3000)}
function updateOperation(){if(!state.order.active)return;const gross=(state.currentPrice/state.order.entry-1)*100,net=gross-state.order.fees*100,targetPct=+$('#profitTarget').value,remaining=Math.max(0,targetPct-net),progress=Math.max(0,Math.min(100,net/targetPct*100));$('#netProfit').textContent=(net>=0?'+':'')+net.toFixed(2).replace('.',',')+'%';$('#remainingProfit').textContent=remaining.toFixed(2).replace('.',',')+'%';$('#progressLabel').textContent=Math.round(progress)+'%';$('#goalProgress').style.width=progress+'%';$('#currentPin').style.left=progress+'%';const distance=(state.order.target-state.currentPrice)/state.order.target*100;if(distance<=.2&&distance>0&&!state.order.approachAlerted){state.order.approachAlerted=true;showGoalAlert(false)}if(state.currentPrice>=state.order.target&&!state.order.targetAlerted){state.order.targetAlerted=true;showGoalAlert(true)}}
function selectStrategy(key){state.strategy=key;const s=strategies[key];$$('.strategy-card').forEach(c=>c.classList.toggle('active',c.dataset.strategy===key));$('#strategyScore').textContent=s.score+' / 100';$('#strategyRisk').textContent=s.risk.toFixed(1).replace('.',',')+'%';$('#strategyExposure').textContent=s.exposure}
function applyStrategy(){const s=strategies[state.strategy];$('#profitTarget').value=s.target;$('#maxRisk').value=s.risk;$('#targetPercentLabel').textContent='+'+s.target.toFixed(2).replace('.',',')+'%';state.timeframe=s.entry;$$('#timeframes button').forEach(b=>b.classList.toggle('active',b.textContent===s.entry));$('#activeStrategy').textContent=s.label+' · '+s.entry+' / '+s.confirm+' / '+s.trend;candles=createCandles(state.currentPrice*.963);calcTarget();drawChart();$('#strategyModal').close();showToast('Estratégia aplicada',s.label+' ajustou gráfico, meta e risco.')}
function setupUI(){
  $$('#timeframes button').forEach(b=>b.onclick=()=>{$$('#timeframes button').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.timeframe=b.textContent;candles=createCandles(state.currentPrice*.963);drawChart()});
  $('#projectionBtn').onclick=()=>{state.projection=!state.projection;$('#projectionBtn').classList.toggle('active',state.projection);$('.forecast-label').style.display=state.projection?'block':'none';drawChart()};
  $('#resetChart').onclick=()=>{candles=createCandles(state.currentPrice*.963);drawChart()};
  $('#fullscreenBtn').onclick=()=>$('#chartWrap').requestFullscreen?.();
  $('#themeBtn').onclick=()=>{document.body.classList.toggle('light');state.theme=document.body.classList.contains('light')?'light':'dark';drawChart()};
  $('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('open');
  $$('.nav-item').forEach(n=>n.onclick=()=>{$$('.nav-item').forEach(x=>x.classList.remove('active'));n.classList.add('active');if(n.dataset.view==='Estratégias')$('#strategyModal').showModal();if(innerWidth<980)$('#sidebar').classList.remove('open')});
  $('#newTradeBtn').onclick=openTrade;$('#simulateBtn').onclick=openTrade;
  $$('#tradeForm input').forEach(i=>i.addEventListener('input',calcTarget));
  $('#confirmTrade').onclick=e=>{e.preventDefault();const target=calcTarget(),entry=state.currentPrice*.9904;state.order={active:true,entry,target,fees:(+$('#buyFee').value+ +$('#sellFee').value+2*(+$('#slippage').value))/100,approachAlerted:false,targetAlerted:false};$('#entryPrice').textContent=fmt(entry);$('#targetPrice').textContent=fmt(target);$('#targetPercentLabel').textContent='+'+(+$('#profitTarget').value).toFixed(2).replace('.',',')+'%';$('#tradeModal').close();$('.status-pill').textContent='● Em andamento';$('#exitTradeBtn').disabled=false;showToast('Operação simulada criada','Agora acompanhamos sua meta líquida.');updateOperation()};
  $$('.strategy-card').forEach(c=>c.onclick=()=>selectStrategy(c.dataset.strategy));$('#applyStrategy').onclick=e=>{e.preventDefault();applyStrategy()};
  $('#exitTradeBtn').disabled=true;$('#exitTradeBtn').onclick=()=>{if(!state.order.active)return;const net=(state.currentPrice/state.order.entry-1)*100-state.order.fees*100;state.order.active=false;$('.status-pill').textContent='● Encerrada';$('#exitTradeBtn').disabled=true;showToast('Saída registrada',(net>=0?'+':'')+net.toFixed(2).replace('.',',')+'% de resultado líquido.','exit')};
  $('#trailingBtn').onclick=()=>{$('#trailingBtn').classList.toggle('active');$('#trailingBtn').textContent=$('#trailingBtn').classList.contains('active')?'✓ Trailing stop ativo':'◇ Ativar trailing stop'};
  window.addEventListener('resize',drawChart); document.addEventListener('fullscreenchange',()=>setTimeout(drawChart,50));
}
function tick(){const pulse=(Math.random()-.46)*12;state.currentPrice+=pulse;candles.at(-1).close=state.currentPrice;candles.at(-1).high=Math.max(candles.at(-1).high,state.currentPrice);candles.at(-1).low=Math.min(candles.at(-1).low,state.currentPrice);$('#currentPrice').textContent=fmt(state.currentPrice);updateOperation();drawChart()}
setupSearch();setupUI();setupChartInteraction();calcTarget();drawChart();setInterval(tick,4200);
