const $ = (s) => document.querySelector(s);
const $$ = (s) => [...document.querySelectorAll(s)];
const state = { asset:'BTC', marketSymbol:'BTCUSDT', timeframe:'15m', projection:true, theme:'dark', currentPrice:64872.4, strategy:'intraday', dataSource:'simulated', markets:[], marketsLoadedAt:0, marketsLoading:false, marketChanging:false, lastLiveRefresh:0, liveRefreshing:false, liveFailures:0, order:{active:false,entry:0,target:0,stop:0,fees:.003,owner:'manual',marketSymbol:'BTCUSDT',investment:0,riskPercent:1.5,trailing:false,peakPrice:0,approachAlerted:false,targetAlerted:false}, robot:{active:false,starting:false,strategy:'intraday',investment:500,maxTrades:3,trades:[],position:null,sessionProfit:0,lastActionAt:0,lastScore:0,stopRequested:false}, portfolio:{initialBalance:1000,balance:1000,trades:[],alerts:[],notifications:[]}, settings:{language:'pt',currency:'USD',fxRates:{USD:1,EUR:.87,BRL:5.55},fxDate:null,googleClientId:'',profile:null} };
const strategies={boost:{label:'Boost agressivo',entry:'5m',confirm:'5m',trend:'15m',score:58,target:.2,risk:.6,exposure:'Agressivo',cooldown:8000,reversal:28,suggestedTrades:10},scalping:{label:'Scalping conservador',entry:'5m',confirm:'15m',trend:'1h',score:74,target:.8,risk:.8,exposure:'Reduzido',cooldown:30000,reversal:35},intraday:{label:'Intraday',entry:'15m',confirm:'1h',trend:'4h',score:70,target:2,risk:1.5,exposure:'Moderado',cooldown:30000,reversal:35},swing:{label:'Swing trade',entry:'4h',confirm:'1D',trend:'1S',score:68,target:4,risk:2.5,exposure:'Ampliado',cooldown:30000,reversal:35}};
const timeframeConfigs={
  '5m':{seed:5,vol:.0038,trend:.00024,labels:['10:00','11:00','12:00','13:00','14:00','15:00','16:00']},
  '15m':{seed:15,vol:.0058,trend:.00042,labels:['10:00','12:00','14:00','16:00','18:00','20:00','22:00']},
  '1h':{seed:60,vol:.0074,trend:.00058,labels:['03:00','06:00','09:00','12:00','15:00','18:00','21:00']},
  '4h':{seed:240,vol:.0096,trend:.00072,labels:['seg','ter','qua','qui','sex','sáb','dom']},
  '1D':{seed:1440,vol:.0125,trend:.00088,labels:['02 jul','06 jul','10 jul','14 jul','18 jul','22 jul','26 jul']},
  '1S':{seed:10080,vol:.016,trend:.00105,labels:['fev','mar','abr','mai','jun','jul','ago']}
};
const assets = [
  {marketSymbol:'BTCUSDT',symbol:'BTC',name:'Bitcoin',price:64872.40,change:1.82,high:65214.90,low:63108.20,volume:38400000000,icon:'₿',color:'#f2a900',live:false},
  {marketSymbol:'ETHUSDT',symbol:'ETH',name:'Ethereum',price:3448.18,change:2.41,high:3512.45,low:3341.20,volume:16200000000,icon:'◆',color:'#667fea',live:false},
  {marketSymbol:'SOLUSDT',symbol:'SOL',name:'Solana',price:158.72,change:4.12,high:162.31,low:150.84,volume:3280000000,icon:'S',color:'#8b5cf6',live:false},
  {marketSymbol:'BNBUSDT',symbol:'BNB',name:'BNB',price:587.31,change:.74,high:593.40,low:579.12,volume:1410000000,icon:'B',color:'#f3ba2f',live:false}
];
const BINANCE_BASES=['https://data-api.binance.vision','https://api.binance.com'];
const binanceIntervals={'5m':'5m','15m':'15m','1h':'1h','4h':'4h','1D':'1d','1S':'1w'};
const knownAssetNames={BTC:'Bitcoin',ETH:'Ethereum',SOL:'Solana',BNB:'BNB',XRP:'XRP',ADA:'Cardano',DOGE:'Dogecoin',AVAX:'Avalanche',DOT:'Polkadot',LINK:'Chainlink',LTC:'Litecoin',BCH:'Bitcoin Cash',TRX:'TRON',TON:'Toncoin',SUI:'Sui',APT:'Aptos',NEAR:'NEAR Protocol',UNI:'Uniswap',AAVE:'Aave',SHIB:'Shiba Inu',PEPE:'Pepe'};
const APP_SETTINGS_KEY='vela-app-settings-v2';
const currencyInfo={USD:{locale:'en-US',symbol:'$'},EUR:{locale:'pt-PT',symbol:'€'},BRL:{locale:'pt-BR',symbol:'R$'}};
const displayCurrency=()=>state.settings?.currency||'USD';
const displayRate=()=>Math.max(.000001,Number(state.settings?.fxRates?.[displayCurrency()])||1);
const fromBaseAmount=value=>(Number(value)||0)*displayRate();
const toBaseAmount=value=>(Number(value)||0)/displayRate();
const currencySymbol=()=>currencyInfo[displayCurrency()]?.symbol||'$';
const displayPair=()=>`${state.asset}/${displayCurrency()}`;
function formatMoney(value,digits=2){const currency=displayCurrency(),locale=state.settings?.language==='en'?'en-US':currencyInfo[currency]?.locale||'pt-BR';return new Intl.NumberFormat(locale,{style:'currency',currency,minimumFractionDigits:digits,maximumFractionDigits:digits}).format(fromBaseAmount(value))}
const fmt = (n, digits=2) => formatMoney(Number(n)||0,digits);
const compactMoney=n=>new Intl.NumberFormat(state.settings?.language==='en'?'en-US':'pt-BR',{style:'currency',currency:displayCurrency(),notation:'compact',maximumFractionDigits:1}).format(fromBaseAmount(n));
const priceDigits=n=>{const converted=fromBaseAmount(n);return converted>=100?2:converted>=1?3:converted>=.01?5:8};
const formatPrice=n=>fmt(Number(n)||0,priceDigits(Number(n)||0));
const coinColor=s=>`hsl(${[...s].reduce((a,c)=>a+c.charCodeAt(0),0)*37%360} 65% 48%)`;
const escapeHtml=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const uiText={
  pt:{login:'Login',settings:'Configurações',general:'Geral',account:'Conta Google',overview:'Visão geral',markets:'Mercados',strategies:'Estratégias',robot:'Robô Trade',wallet:'Carteira',paper:'Paper trades',alerts:'Alertas',search:'Buscar ativo, ex. ETH ou Solana',high:'Máxima 24h',low:'Mínima 24h',volume:'Volume 24h',source:'Fonte',probable:'Entrada provável',signalWhy:'Por que este sinal?',openTrade:'Registrar entrada simulada',closeTrade:'Registrar saída e fechar operação',language:'Idioma',currency:'Moeda padrão',fx:'Câmbio automático',refresh:'↻ Atualizar',connected:'CONTA CONECTADA',noAccount:'Nenhuma conta',signIn:'Faça login com o Google',logout:'Sair da conta Google',projection:'PROJEÇÃO · 24 CANDLES',boostProjection:'PROJEÇÃO BOOST · RECUPERAÇÃO 0×0'},
  en:{login:'Login',settings:'Settings',general:'General',account:'Google Account',overview:'Overview',markets:'Markets',strategies:'Strategies',robot:'Trade Bot',wallet:'Wallet',paper:'Paper trades',alerts:'Alerts',search:'Search asset, e.g. ETH or Solana',high:'24h high',low:'24h low',volume:'24h volume',source:'Source',probable:'Probable entry',signalWhy:'Why this signal?',openTrade:'Register simulated entry',closeTrade:'Register exit and close trade',language:'Language',currency:'Default currency',fx:'Automatic FX',refresh:'↻ Refresh',connected:'CONNECTED ACCOUNT',noAccount:'No account',signIn:'Sign in with Google',logout:'Sign out of Google',projection:'PROJECTION · 24 CANDLES',boostProjection:'BOOST PROJECTION · BREAK-EVEN RECOVERY'}
};
const tr=key=>uiText[state.settings?.language]?.[key]||uiText.pt[key]||key;
function restoreAppSettings(){
  let saved={};try{saved=JSON.parse(localStorage.getItem(APP_SETTINGS_KEY)||'{}')||{}}catch(error){saved={}}
  const language=['pt','en'].includes(saved.language)?saved.language:'pt',currency=['USD','EUR','BRL'].includes(saved.currency)?saved.currency:'USD';
  const rates={...state.settings.fxRates,...(saved.fxRates||{}),USD:1},metaClientId=document.querySelector('meta[name="google-client-id"]')?.content?.trim()||'';
  state.settings={language,currency,fxRates:rates,fxDate:saved.fxDate||null,googleClientId:saved.googleClientId||metaClientId,profile:saved.profile&&saved.profile.email?saved.profile:null};
}
function saveAppSettings(){try{localStorage.setItem(APP_SETTINGS_KEY,JSON.stringify(state.settings))}catch(error){/* preferências seguem disponíveis nesta sessão */}}
function setText(selector,text){const element=$(selector);if(element)element.textContent=text}
function applyLanguage(){
  document.documentElement.lang=state.settings.language==='en'?'en':'pt-BR';
  const navKeys=['overview','markets','strategies','robot','wallet','paper','alerts'];$$('.main-nav .nav-item').forEach((item,index)=>{const label=item.querySelectorAll('span')[1];if(label&&navKeys[index])label.textContent=tr(navKeys[index])});
  $('#assetSearch').placeholder=tr('search');setText('#loginButtonText',state.settings.profile?.name?.split(' ')[0]||tr('login'));setText('#settingsTitle',tr('settings'));
  const tabs=$$('.settings-tabs button');if(tabs[0])tabs[0].textContent=tr('general');if(tabs[1])tabs[1].textContent=tr('account');
  const statLabels=$$('.market-stats small');[tr('high'),tr('low'),tr('volume'),tr('source')].forEach((text,index)=>{if(statLabels[index])statLabels[index].textContent=text});
  setText('.score-panel h2',tr('probable'));setText('#simulateBtn',tr('openTrade')+' →');setText('#closeTradeBtn',tr('closeTrade')+' ↘');setText('.context-panel h2',tr('signalWhy'));
  const fields=$$('.settings-field>span>strong');if(fields[0])fields[0].textContent=tr('language');if(fields[1])fields[1].textContent=tr('currency');setText('#fxStatusTitle',tr('fx'));setText('#refreshFxBtn',tr('refresh'));setText('#logoutGoogleBtn',tr('logout'));
  updateProfileUI();updateForecastLabel();
}
function robotNet(position){return position?(state.currentPrice/position.entry-1)*100-position.fees*100:0}
function updateForecastLabel(){const element=$('#forecastLabel');if(!element)return;const locked=state.robot.strategy==='boost'&&state.robot.position&&robotNet(state.robot.position)<-1e-8;element.innerHTML=`<span></span> ${tr(locked?'boostProjection':'projection')}`;element.classList.toggle('boost-lock',!!locked)}
function updateProfileUI(){
  const profile=state.settings.profile,avatarMarkup=profile?.picture?`<img src="${escapeHtml(profile.picture)}" alt="">`:(profile?.name?.[0]||'G').toUpperCase();
  $('#profileAvatar').innerHTML=avatarMarkup;$('#loginAvatar').innerHTML=avatarMarkup;setText('#profileName',profile?.name||tr('noAccount'));setText('#profileEmail',profile?.email||tr('signIn'));setText('#loginButtonText',profile?.name?.split(' ')[0]||tr('login'));$('#logoutGoogleBtn').hidden=!profile;
}
function openSettings(tab='general'){$$('.settings-tabs button').forEach(button=>button.classList.toggle('active',button.dataset.settingsTab===tab));$$('.settings-panel').forEach(panel=>panel.classList.toggle('active',panel.dataset.settingsPanel===tab));const dialog=$('#settingsModal');if(typeof dialog?.showModal==='function'&&!dialog.open)dialog.showModal();if(tab==='account')configureGoogleSignIn()}
function decodeGoogleCredential(token){try{const payload=token.split('.')[1].replace(/-/g,'+').replace(/_/g,'/'),json=decodeURIComponent(atob(payload).split('').map(char=>'%'+char.charCodeAt(0).toString(16).padStart(2,'0')).join(''));return JSON.parse(json)}catch(error){return null}}
function handleGoogleCredential(response){const payload=decodeGoogleCredential(response?.credential||'');if(!payload?.email){showToast('Login Google inválido','Não foi possível ler os dados da conta.','exit');return}state.settings.profile={id:payload.sub||'',name:payload.name||payload.email,email:payload.email,picture:payload.picture||''};saveAppSettings();updateProfileUI();showToast(state.settings.language==='en'?'Google account connected':'Conta Google conectada',payload.email)}
let configuredGoogleClientId='';
function configureGoogleSignIn(){
  const wrap=$('#googleSignInWrap'),clientId=state.settings.googleClientId;$('#googleClientId').value=clientId||'';
  if(!clientId){wrap.innerHTML='<span>Configure o Client ID para habilitar o login Google.</span>';return}
  if(!globalThis.google?.accounts?.id){wrap.innerHTML='<span>Carregando Google Identity Services...</span>';setTimeout(configureGoogleSignIn,700);return}
  try{if(configuredGoogleClientId!==clientId){google.accounts.id.initialize({client_id:clientId,callback:handleGoogleCredential,auto_select:false});configuredGoogleClientId=clientId}wrap.innerHTML='';google.accounts.id.renderButton(wrap,{theme:state.theme==='light'?'outline':'filled_black',size:'large',shape:'pill',text:'signin_with',locale:state.settings.language==='en'?'en':'pt-BR',width:280})}catch(error){wrap.innerHTML='<span>Client ID não autorizado para este domínio.</span>'}
}
async function refreshFxRates(showFeedback=false){
  const status=$('#fxStatusText');if(status)status.textContent=state.settings.language==='en'?'Updating public rates...':'Atualizando cotações públicas...';
  try{const oldRate=displayRate(),[eurResponse,brlResponse]=await Promise.all([fetch('https://api.frankfurter.dev/v2/rate/USD/EUR'),fetch('https://api.frankfurter.dev/v2/rate/USD/BRL')]);if(!eurResponse.ok||!brlResponse.ok)throw new Error('FX indisponível');const [eur,brl]=await Promise.all([eurResponse.json(),brlResponse.json()]);if(!Number.isFinite(eur.rate)||!Number.isFinite(brl.rate))throw new Error('Cotação inválida');state.settings.fxRates={USD:1,EUR:eur.rate,BRL:brl.rate};state.settings.fxDate=eur.date||brl.date||new Date().toISOString().slice(0,10);const newRate=displayRate();['#investment','#robotInvestment','#initialBalanceInput','#alertTarget'].forEach(selector=>updateMoneyInput(selector,oldRate,newRate));saveAppSettings();applyCurrencyUI(null,false);if(showFeedback)showToast('Câmbio atualizado',`USD/EUR ${eur.rate.toFixed(4)} · USD/BRL ${brl.rate.toFixed(4)}`)}catch(error){if(status)status.textContent=state.settings.language==='en'?'Offline fallback rates in use':'Usando cotações locais de segurança';if(showFeedback)showToast('Câmbio indisponível','Mantivemos a última cotação salva.','exit')}
}
function updateMoneyInput(selector,oldRate,newRate){const input=$(selector);if(!input||input.value===''||!Number.isFinite(Number(input.value)))return;const base=Number(input.value)/Math.max(.000001,oldRate);input.value=(base*newRate).toFixed(selector==='#alertTarget'?priceDigits(base):2)}
function applyCurrencyUI(oldCurrency='USD',convertInputs=true){
  const newCurrency=displayCurrency(),oldRate=Number(state.settings.fxRates?.[oldCurrency])||1,newRate=displayRate();
  if(convertInputs)['#investment','#robotInvestment','#initialBalanceInput','#alertTarget'].forEach(selector=>updateMoneyInput(selector,oldRate,newRate));
  ['#investment','#robotInvestment','#initialBalanceInput','#alertTarget'].forEach(selector=>{const input=$(selector),prefix=input?.parentElement?.querySelector('b');if(prefix)prefix.textContent=currencySymbol()});
  setText('#assetSymbol',displayPair());setText('#robotPair',displayPair());setText('#alertAsset',displayPair());
  const active=marketBySymbol(state.marketSymbol);if(active)updateAssetHeader(active);else setText('#currentPrice',formatPrice(state.currentPrice));
  calcTarget();renderFinance();renderRobotUI();drawChart();const status=$('#fxStatusText');if(status)status.textContent=`1 USD = ${state.settings.fxRates[newCurrency].toLocaleString(state.settings.language==='en'?'en-US':'pt-BR',{maximumFractionDigits:4})} ${newCurrency}${state.settings.fxDate?' · '+state.settings.fxDate:''}`;
}
function setupSettingsUI(){
  $('#languageSelect').value=state.settings.language;$('#currencySelect').value=state.settings.currency;$('#googleClientId').value=state.settings.googleClientId||'';
  $('#settingsBtn').onclick=()=>openSettings('general');$('#googleLoginBtn').onclick=()=>openSettings('account');$('#closeSettings').onclick=()=>$('#settingsModal').close();
  $$('.settings-tabs button').forEach(button=>button.onclick=()=>openSettings(button.dataset.settingsTab));
  $('#languageSelect').onchange=()=>{state.settings.language=$('#languageSelect').value;saveAppSettings();applyLanguage();renderFinance();renderRobotUI();drawChart();configureGoogleSignIn()};
  $('#currencySelect').onchange=()=>{const old=state.settings.currency;state.settings.currency=$('#currencySelect').value;saveAppSettings();applyCurrencyUI(old,true)};
  $('#refreshFxBtn').onclick=()=>refreshFxRates(true);$('#saveGoogleClientId').onclick=()=>{const value=$('#googleClientId').value.trim();if(value&&!value.endsWith('.apps.googleusercontent.com')){showToast('Client ID inválido','Use o identificador terminado em .apps.googleusercontent.com.','exit');return}state.settings.googleClientId=value;configuredGoogleClientId='';saveAppSettings();configureGoogleSignIn();showToast('Configuração salva',value?'Login Google habilitado.':'Client ID removido.')};
  $('#logoutGoogleBtn').onclick=()=>{state.settings.profile=null;saveAppSettings();globalThis.google?.accounts?.id?.disableAutoSelect?.();updateProfileUI();showToast('Conta desconectada','Os dados locais do perfil foram removidos.','exit')};
  updateProfileUI();applyLanguage();configureGoogleSignIn();
}
const seeded = (i) => { const x = Math.sin(i * 9283.17 + 74.3) * 43758.5; return x - Math.floor(x); };

function createCandles(base=62500, count=92){
  const config=timeframeConfigs[state.timeframe]||timeframeConfigs['15m'];let p=base; const list=[];
  for(let i=0;i<count;i++){
    const phase=i<20?.8:i<39?-.5:i<66?1.15:.4;
    const drift=config.trend*phase;
    const change=(seeded(i+config.seed)-.48)*config.vol+Math.sin((i+config.seed)*.23)*config.vol*.18+drift;
    const open=p; const close=open*(1+change); const wick=(.0015+seeded(i+200)*.004)*open;
    list.push({open,close,high:Math.max(open,close)+wick*(1+config.vol*35),low:Math.min(open,close)-wick*.8*(1+config.vol*30),volume:38+seeded(i+400+config.seed)*85+(i>64?22:0)}); p=close;
  }
  const scale=state.currentPrice/list.at(-1).close;
  return list.map(c=>({open:c.open*scale,close:c.close*scale,high:c.high*scale,low:c.low*scale,volume:c.volume}));
}
let candles=createCandles();
function ema(data, period){ const k=2/(period+1); let prev=data[0].close; return data.map((d,i)=>{prev=i?d.close*k+prev*(1-k):prev;return prev;}); }
function findProfitableEntries(data){const hits=[];for(let i=8;i<data.length-12;i++){if(hits.length&&i-hits.at(-1).entry<=9)continue;for(let horizon=1;horizon<=11;horizon++){const exit=i+horizon,gain=(data[exit].close/data[i].close-1)*100;if(gain>=.4&&gain<1){hits.push({entry:i,exit,gain});break}}}return hits.slice(-4)}
function drawChart(){
  const canvas=$('#priceChart'), wrap=$('#chartWrap'), dpr=Math.min(devicePixelRatio||1,2); const w=wrap.clientWidth,h=wrap.clientHeight;
  if(!w||!h||!candles.length)return;
  canvas.width=w*dpr; canvas.height=h*dpr; const ctx=canvas.getContext('2d'); ctx.scale(dpr,dpr); ctx.clearRect(0,0,w,h);
  const dark=!document.body.classList.contains('light'); const grid=dark?'#172722':'#e7eeeb', label=dark?'#60756e':'#81928c';
  const pad={l:10,r:61,t:14,b:34}, volH=65, plotH=h-pad.t-pad.b; const visible=candles; const forecastN=18;
  let lows=visible.map(c=>c.low),highs=visible.map(c=>c.high);if(state.order.active){if(Number.isFinite(state.order.stop))lows.push(state.order.stop);if(Number.isFinite(state.order.target))highs.push(state.order.target);if(Number.isFinite(state.order.entry)){lows.push(state.order.entry);highs.push(state.order.entry)}}const min=Math.min(...lows)*.997,max=Math.max(...highs)*1.003; const candleAreaW=(w-pad.l-pad.r)*.79; const step=candleAreaW/visible.length;
  const x=i=>pad.l+(i+.5)*step, y=v=>pad.t+(max-v)/(max-min)*(plotH-volH);
  ctx.font='8px DM Mono'; ctx.fillStyle=label; ctx.textAlign='left';
  for(let i=0;i<6;i++){const yy=pad.t+i*(plotH-volH)/5;ctx.beginPath();ctx.strokeStyle=grid;ctx.setLineDash([2,4]);ctx.moveTo(pad.l,yy);ctx.lineTo(w-pad.r,yy);ctx.stroke();ctx.setLineDash([]);const val=max-i*(max-min)/5;ctx.fillText(fmt(val,0),w-pad.r+8,yy+3)}
  const timeLabels=(timeframeConfigs[state.timeframe]||timeframeConfigs['15m']).labels;wrap.dataset.axisLabels=timeLabels.join('|');for(let i=0;i<7;i++){const xx=pad.l+i*(w-pad.l-pad.r)/6;ctx.beginPath();ctx.strokeStyle=grid;ctx.moveTo(xx,pad.t);ctx.lineTo(xx,h-pad.b);ctx.stroke();ctx.fillText(timeLabels[i],Math.min(xx+2,w-87),h-12)}
  const maxVol=Math.max(...visible.map(c=>c.volume)); visible.forEach((c,i)=>{const xx=x(i),up=c.close>=c.open,col=up?'#4fc49a':'#e36b65';const vy=h-pad.b-(c.volume/maxVol)*volH*.65;ctx.globalAlpha=.18;ctx.fillStyle=col;ctx.fillRect(xx-step*.34,vy,step*.68,h-pad.b-vy);ctx.globalAlpha=1;ctx.strokeStyle=col;ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(xx,y(c.high));ctx.lineTo(xx,y(c.low));ctx.stroke();ctx.fillStyle=col;const top=y(Math.max(c.open,c.close)),bh=Math.max(1.2,Math.abs(y(c.open)-y(c.close)));ctx.fillRect(xx-step*.29,top,step*.58,bh)});
  const series=[{v:ema(visible,9),c:'#65d9ac',w:1.5},{v:ema(visible,21),c:'#e8bc69',w:1.15},{v:ema(visible,50),c:'#9678ef',w:1.15}];
  series.forEach(s=>{ctx.beginPath();ctx.strokeStyle=s.c;ctx.lineWidth=s.w;s.v.forEach((v,i)=>i?ctx.lineTo(x(i),y(v)):ctx.moveTo(x(i),y(v)));ctx.stroke()});
  $('#ema9Label').textContent=fmt(series[0].v.at(-1),0);$('#ema21Label').textContent=fmt(series[1].v.at(-1),0);$('#ema50Label').textContent=fmt(series[2].v.at(-1),0);const volumeSum=visible.reduce((a,c)=>a+c.volume,0),vwap=visible.reduce((a,c)=>a+c.close*c.volume,0)/volumeSum;$('#vwapLabel').textContent=fmt(vwap,0);
  const profitableEntries=findProfitableEntries(visible);wrap.dataset.markerCount=profitableEntries.length;wrap.dataset.markerGains=profitableEntries.map(h=>h.gain.toFixed(2)).join(',');wrap.dataset.timeframe=state.timeframe;wrap.dataset.seriesSignature=visible.slice(0,6).map(c=>c.close.toFixed(2)).join('|');profitableEntries.forEach(hit=>{const ex=x(hit.entry),ey=y(visible[hit.entry].low)-13;ctx.save();ctx.shadowColor='rgba(101,217,172,.65)';ctx.shadowBlur=9;ctx.fillStyle='#65d9ac';ctx.beginPath();ctx.moveTo(ex,ey-10);ctx.lineTo(ex-8,ey+4);ctx.lineTo(ex+8,ey+4);ctx.closePath();ctx.fill();ctx.restore();ctx.fillStyle=dark?'#173a30':'#d9f4e9';ctx.fillRect(ex-22,ey+7,44,14);ctx.fillStyle=dark?'#8cf0c8':'#106b4e';ctx.font='700 8px DM Mono';ctx.textAlign='center';ctx.fillText('+'+hit.gain.toFixed(2)+'%',ex,ey+17);const xx=x(hit.exit),xy=y(visible[hit.exit].high)+13;ctx.save();ctx.shadowColor='rgba(238,116,109,.55)';ctx.shadowBlur=8;ctx.fillStyle='#ee746d';ctx.beginPath();ctx.moveTo(xx,xy+10);ctx.lineTo(xx-8,xy-4);ctx.lineTo(xx+8,xy-4);ctx.closePath();ctx.fill();ctx.restore();ctx.fillStyle=dark?'#40201e':'#fae2e0';ctx.fillRect(xx-20,xy-23,40,13);ctx.fillStyle=dark?'#ff9a94':'#9b2f2a';ctx.font='700 7px DM Mono';ctx.fillText('SAÍDA',xx,xy-14);ctx.textAlign='left'});
  if(state.projection){const start=visible.at(-1).close,sx=x(visible.length-1),fw=(w-pad.r-sx),points=forecastN+1,boostPosition=state.robot.strategy==='boost'?state.robot.position:null,breakEven=boostPosition?.breakEven||boostPosition?.entry*(1+Number(boostPosition?.fees||0)),recovery=boostPosition&&robotNet(boostPosition)<0,signalDrift=Math.max(-.012,Math.min(.022,(calculateRobotSignal().score-50)/2500)),recoveryDrift=recovery?Math.max(0,Math.min(.035,breakEven/start-1)):.0184,drift=recovery?Math.max(recoveryDrift,signalDrift):signalDrift+.009;const med=Array.from({length:points},(_,i)=>start*(1+drift*(i/forecastN)+Math.sin(i*.7)*.0012));const band=(mult)=>med.map((v,i)=>v*(1+mult*Math.sqrt(i/forecastN)));
    const outerUp=band(.018),outerDn=band(-.018),innerUp=band(.009),innerDn=band(-.009);ctx.save();ctx.beginPath();ctx.rect(sx,0,w-sx,h);ctx.clip();const area=(up,dn,color)=>{ctx.beginPath();up.forEach((v,i)=>i?ctx.lineTo(sx+i*fw/forecastN,y(v)):ctx.moveTo(sx,y(v)));[...dn].reverse().forEach((v,j)=>ctx.lineTo(sx+(forecastN-j)*fw/forecastN,y(v)));ctx.closePath();ctx.fillStyle=color;ctx.fill()};area(outerUp,outerDn,dark?'rgba(101,217,172,.045)':'rgba(22,141,103,.06)');area(innerUp,innerDn,dark?'rgba(101,217,172,.10)':'rgba(22,141,103,.12)');ctx.beginPath();ctx.strokeStyle='#65d9ac';ctx.setLineDash([4,4]);ctx.lineWidth=1.2;med.forEach((v,i)=>i?ctx.lineTo(sx+i*fw/forecastN,y(v)):ctx.moveTo(sx,y(v)));ctx.stroke();ctx.restore();ctx.setLineDash([]);ctx.beginPath();ctx.strokeStyle=dark?'#315047':'#a9beb6';ctx.setLineDash([3,4]);ctx.moveTo(sx,pad.t);ctx.lineTo(sx,h-pad.b);ctx.stroke();ctx.setLineDash([])}
  const suggestedEntry=state.currentPrice,entry=state.order.active?state.order.entry:suggestedEntry,target=state.order.active?state.order.target:suggestedEntry*1.02306,boostLocked=state.robot.strategy==='boost'&&state.robot.position,stop=boostLocked?(state.robot.position.breakEven||entry*(1+state.order.fees)):(state.order.active&&state.order.stop?state.order.stop:suggestedEntry*.98635);const levels=[{v:target,c:'#65d9ac',t:'ALVO'},{v:entry,c:'#7e918b',t:'ENTRADA'},{v:stop,c:boostLocked?'#ffc567':'#ee746d',t:boostLocked?'TRAVA 0×0':'STOP'}];levels.forEach(l=>{ctx.beginPath();ctx.strokeStyle=l.c;ctx.globalAlpha=.52;ctx.setLineDash([5,5]);ctx.moveTo(pad.l,y(l.v));ctx.lineTo(w-pad.r,y(l.v));ctx.stroke();ctx.globalAlpha=1;ctx.setLineDash([]);ctx.fillStyle=l.c;ctx.fillRect(w-pad.r,y(l.v)-8,53,15);ctx.fillStyle=dark?'#07100f':'#fff';ctx.font='700 6px Manrope';ctx.fillText(l.t,w-pad.r+5,y(l.v)+2)});
  const cy=y(visible.at(-1).close),cx=x(visible.length-1);ctx.fillStyle='#65d9ac';ctx.beginPath();ctx.arc(cx,cy,2.5,0,Math.PI*2);ctx.fill();ctx.fillStyle='#65d9ac';ctx.fillRect(w-pad.r,cy-8,55,16);ctx.fillStyle='#07100f';ctx.font='600 7px DM Mono';ctx.fillText(fmt(visible.at(-1).close,0),w-pad.r+5,cy+2);const pulse=$('#currentPricePulse');pulse.style.left=cx+'px';pulse.style.top=cy+'px';
  canvas._map={x,y,step,min,max,pad,w,h};
}

function setupChartInteraction(){const canvas=$('#priceChart'),tip=$('#chartTooltip');canvas.addEventListener('mousemove',e=>{const m=canvas._map;if(!m)return;const rect=canvas.getBoundingClientRect(),mx=e.clientX-rect.left;const i=Math.max(0,Math.min(candles.length-1,Math.floor((mx-m.pad.l)/m.step)));const c=candles[i];tip.innerHTML=`<b style="color:${c.close>=c.open?'#65d9ac':'#ee746d'}">${state.asset} · ${state.timeframe}</b><br>O ${fmt(c.open)} &nbsp; H ${fmt(c.high)}<br>L ${fmt(c.low)} &nbsp; C ${fmt(c.close)}<br>Vol ${c.volume.toFixed(1)} mi`;tip.style.left=Math.min(mx+12,m.w-165)+'px';tip.style.top=Math.max(10,e.clientY-rect.top-52)+'px';tip.classList.add('show')});canvas.addEventListener('mouseleave',()=>tip.classList.remove('show'))}

async function fetchBinance(path){let lastError;for(const base of BINANCE_BASES){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),8000);try{const response=await fetch(base+path,{signal:controller.signal});if(!response.ok)throw new Error(`Binance ${response.status}`);return await response.json()}catch(error){lastError=error}finally{clearTimeout(timer)}}throw lastError||new Error('API indisponível')}
function marketCatalog(){return state.markets.length?state.markets:assets}
function marketBySymbol(value){const key=String(value||'').toUpperCase();return marketCatalog().find(a=>a.marketSymbol===key||a.symbol===key)||assets.find(a=>a.marketSymbol===key||a.symbol===key)}
function changeLabel(value){const number=Number(value)||0;return`${number>=0?'+':''}${number.toFixed(2).replace('.',',')}%`}
function marketMatches(a,query){const q=query.trim().toLowerCase();return !q||`${a.symbol} ${a.marketSymbol} ${a.name}`.toLowerCase().includes(q)}

async function loadMarkets(force=false){
  if(state.marketsLoading)return;if(!force&&state.markets.length&&Date.now()-state.marketsLoadedAt<300000){renderMarkets($('#marketsSearch')?.value||'');return}
  state.marketsLoading=true;const table=$('#marketTable');if(table)table.innerHTML='<div class="market-loading"><i></i><strong>Consultando mercados</strong><small>Conectando à Binance Spot...</small></div>';
  try{
    const [info,tickers]=await Promise.all([fetchBinance('/api/v3/exchangeInfo'),fetchBinance('/api/v3/ticker/24hr')]);if(!Array.isArray(info?.symbols)||!Array.isArray(tickers))throw new Error('Resposta de mercados inválida');const tickerMap=new Map(tickers.map(t=>[t.symbol,t]));
    state.markets=info.symbols.filter(s=>s.quoteAsset==='USDT'&&s.status==='TRADING'&&s.isSpotTradingAllowed!==false).map(s=>{const t=tickerMap.get(s.symbol)||{};const price=Number(t.lastPrice);return{marketSymbol:s.symbol,symbol:s.baseAsset,name:knownAssetNames[s.baseAsset]||s.baseAsset,price,change:Number(t.priceChangePercent)||0,high:Number(t.highPrice)||price,low:Number(t.lowPrice)||price,volume:Number(t.quoteVolume)||0,icon:s.baseAsset.slice(0,2),color:coinColor(s.baseAsset),live:true}}).filter(a=>Number.isFinite(a.price)&&a.price>0).sort((a,b)=>b.volume-a.volume);
    state.marketsLoadedAt=Date.now();renderMarkets($('#marketsSearch')?.value||'');const active=marketBySymbol(state.marketSymbol);if(active?.live&&state.dataSource==='simulated'){updateAssetHeader(active);await loadMarketCandles()}
  }catch(error){state.markets=[];renderMarkets($('#marketsSearch')?.value||'',true);if($('#marketsModal')?.open)showToast('API temporariamente indisponível','Exibindo os ativos favoritos no modo local.','exit')}
  finally{state.marketsLoading=false;const query=$('#assetSearch')?.value||'';if(query)renderGlobalSearch(query)}
}

function renderMarkets(query='',fallback=false){
  const table=$('#marketTable');if(!table)return;const catalog=marketCatalog(),filtered=catalog.filter(a=>marketMatches(a,query));$('#marketCount').textContent=catalog.length;$('#marketsUpdated').textContent=fallback?'Modo local · tente atualizar':state.markets.length?`Atualizado às ${new Date(state.marketsLoadedAt).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}`:'Favoritos locais';
  table.innerHTML=filtered.slice(0,80).map(a=>`<button class="market-row" data-market="${escapeHtml(a.marketSymbol)}"><span class="market-asset"><i class="market-coin" style="background:${a.color}">${escapeHtml(a.icon)}</i><b>${escapeHtml(a.name)}<small>${escapeHtml(a.symbol)}/${displayCurrency()}</small></b></span><strong class="market-number">${formatPrice(a.price)}</strong><strong class="market-change ${a.change>=0?'up':'down'}">${changeLabel(a.change)}</strong><span class="market-volume">${compactMoney(a.volume)}</span></button>`).join('')||'<div class="market-empty"><strong>Nenhum mercado encontrado</strong><small>Tente pesquisar pelo símbolo, como BTC, ETH ou XRP.</small></div>';
  $$('.market-row[data-market]').forEach(row=>row.onclick=()=>selectMarket(row.dataset.market))
}

function updateAssetHeader(a){
  state.asset=a.symbol;state.marketSymbol=a.marketSymbol;state.currentPrice=a.price;state.dataSource=a.live?'binance':'simulated';state.liveFailures=0;$('#assetName').textContent=a.name;$('#assetSymbol').textContent=`${a.symbol} / ${displayCurrency()}`;$('#coinLogo').textContent=a.icon;$('#coinLogo').style.background=a.color;$('#currentPrice').textContent=formatPrice(a.price);const change=$('.price-change');change.textContent=changeLabel(a.change);change.classList.toggle('negative',a.change<0);$('#statHigh').textContent=formatPrice(a.high);$('#statLow').textContent=formatPrice(a.low);$('#statVolume').textContent=compactMoney(a.volume);$('#statSource').textContent=a.live?`Binance · ${displayCurrency()}`:'Simulação';if(!state.order.active){const entry=a.price,stop=entry*.98635;$('#entryPrice').textContent=formatPrice(entry);$('#stopPrice').textContent=formatPrice(stop)}calcTarget();renderAlerts()
}

async function loadMarketCandles(){
  if(state.dataSource!=='binance'){candles=createCandles(state.currentPrice*.963);drawChart();return}
  try{const rows=await fetchBinance(`/api/v3/klines?symbol=${encodeURIComponent(state.marketSymbol)}&interval=${binanceIntervals[state.timeframe]||'15m'}&limit=92`);if(!Array.isArray(rows))throw new Error('Resposta de candles inválida');const parsed=rows.map(k=>({time:Number(k[0]),open:Number(k[1]),high:Number(k[2]),low:Number(k[3]),close:Number(k[4]),volume:Number(k[5])})).filter(c=>[c.open,c.high,c.low,c.close,c.volume].every(Number.isFinite)&&c.high>=c.low&&c.volume>=0);if(parsed.length<50)throw new Error('Candles insuficientes');candles=parsed;state.currentPrice=candles.at(-1).close;state.liveFailures=0;$('#currentPrice').textContent=formatPrice(state.currentPrice);drawChart()}
  catch(error){state.dataSource='simulated';$('#statSource').textContent='Fallback local';candles=createCandles(state.currentPrice*.963);drawChart();showToast('Candles indisponíveis','O gráfico continuou no modo local.','exit')}
}

async function selectMarket(value){const a=marketBySymbol(value);if(!a||state.marketChanging)return;if(state.order.active&&state.order.marketSymbol&&state.order.marketSymbol!==a.marketSymbol){showToast('Operação em andamento','Encerre a posição atual antes de trocar de mercado.','exit');return}state.marketChanging=true;try{updateAssetHeader(a);$('#searchResults').classList.remove('show');$('#assetSearch').value='';if($('#marketsModal')?.open)$('#marketsModal').close();await loadMarketCandles();renderRobotUI();showToast(`${a.symbol}/${displayCurrency()} selecionado`,state.dataSource==='binance'?'Candles carregados da Binance Spot.':'Ativo aberto no modo local.')}finally{state.marketChanging=false;if(state.robot.active)runRobot()}}
function chooseAsset(symbol){return selectMarket(symbol)}

function renderGlobalSearch(query){const box=$('#searchResults'),found=marketCatalog().filter(a=>marketMatches(a,query)).slice(0,10);box.innerHTML=found.map(a=>`<button class="search-option" data-market="${escapeHtml(a.marketSymbol)}"><strong><i style="background:${a.color}">${escapeHtml(a.icon)}</i>${escapeHtml(a.name)}</strong><span>${escapeHtml(a.symbol)}/${displayCurrency()} · ${formatPrice(a.price)}</span></button>`).join('')||'<div class="search-option"><span>Nenhum ativo encontrado na Binance.</span></div>';box.classList.toggle('show',!!query);$$('.search-option[data-market]').forEach(el=>el.onclick=()=>selectMarket(el.dataset.market))}
function setupSearch(){const input=$('#assetSearch'),marketsInput=$('#marketsSearch');input.addEventListener('focus',()=>loadMarkets());input.addEventListener('input',async e=>{const query=e.target.value;renderGlobalSearch(query);if(!state.markets.length){await loadMarkets();if(input.value===query)renderGlobalSearch(query)}});marketsInput?.addEventListener('input',e=>renderMarkets(e.target.value));document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();input.focus()}});document.addEventListener('click',e=>{if(!e.target.closest('.search-wrap'))$('#searchResults').classList.remove('show')})}

function calculateRobotSignal(){
  const strategy=strategies[state.robot.strategy]||strategies.intraday;if(candles.length<50)return{score:0,label:'Aguardando dados',strategy,momentum:0,volumeRatio:0};
  const ema9=ema(candles,9),ema21=ema(candles,21),ema50=ema(candles,50),last=candles.at(-1),previous=candles.at(-4)||candles[0],volumes=candles.slice(-21,-1).map(c=>c.volume),averageVolume=volumes.reduce((a,b)=>a+b,0)/Math.max(1,volumes.length),volumeRatio=last.volume/Math.max(averageVolume,.000001),momentum=(last.close/previous.close-1)*100,candleRange=Math.max(last.high-last.low,.000001),candleStrength=(last.close-last.open)/candleRange;let score=25;
  score+=ema9.at(-1)>ema21.at(-1)?20:-10;score+=ema21.at(-1)>ema50.at(-1)?18:-8;score+=last.close>ema9.at(-1)?12:-6;score+=momentum>.08?12:momentum>0?7:-7;score+=volumeRatio>1.15?8:volumeRatio>.85?4:0;score+=candleStrength>.2?5:candleStrength<-.35?-5:0;score=Math.max(0,Math.min(100,Math.round(score)));const label=score>=strategy.score?'Entrada inteligente':score>=strategy.score-10?'Observando sinal':'Aguardando alinhamento';return{score,label,strategy,momentum,volumeRatio,ema9:ema9.at(-1),ema21:ema21.at(-1),ema50:ema50.at(-1)}
}
function updateRobotRules(){const key=$('#robotStrategy').value,s=strategies[key]||strategies.intraday;$('#robotRules').innerHTML=key==='boost'?`<span><i>✓</i> Entrada: confiança mínima de ${s.score}</span><span><i>✓</i> Meta líquida: +${s.target.toFixed(2).replace('.',',')}%</span><span class="boost-lock"><i>✓</i> Trava 0×0: nenhuma saída negativa</span><span><i>✓</i> Projeção adaptativa até o breakeven</span>`:`<span><i>✓</i> Entrada: confiança mínima de ${s.score}</span><span><i>✓</i> Meta líquida: +${s.target.toFixed(2).replace('.',',')}%</span><span><i>✓</i> Stop líquido: −${s.risk.toFixed(1).replace('.',',')}%</span><span><i>✓</i> Nova leitura em ${Math.round(s.cooldown/1000)}s</span>`}
function renderRobotHistory(){const history=$('#robotHistory'),trades=state.robot.trades;$('#robotTradeCount').textContent=`${trades.length} ${trades.length===1?'operação':'operações'}`;history.innerHTML=trades.length?trades.map(t=>`<div class="robot-history-row"><span><strong>${escapeHtml(t.symbol)}/${displayCurrency()}</strong><small>${escapeHtml(t.reason)}</small></span><span><strong>${escapeHtml(t.strategy)}</strong><small>${t.time}</small></span><span><strong>${formatPrice(t.entry)} → ${formatPrice(t.exit)}</strong><small>${t.score}/100 na entrada</small></span><b class="${t.net>=0?'profit':'loss'}">${t.net>=0?'+':''}${t.net.toFixed(2).replace('.',',')}%<small>${t.value>=0?'+':''}${fmt(t.value)}</small></b></div>`).join(''):'<div class="robot-history-empty"><span>◎</span><strong>Nenhuma operação nesta sessão</strong><small>Os registros aparecerão aqui após o robô encontrar um sinal válido.</small></div>'}
function robotGoalProgress(position){const price=state.currentPrice,neutral=position.protection==='breakeven'?position.breakEven:position.entry,upRange=Math.max(position.target-neutral,Number.EPSILON),downRange=Math.max(neutral-position.stop,Number.EPSILON),raw=price>=neutral?50+50*(price-neutral)/upRange:50-50*(neutral-price)/downRange,progress=Math.max(0,Math.min(100,raw));return{progress,remaining:Math.max(0,100-progress)}}
function renderRobotUI(signal=calculateRobotSignal()){
  const r=state.robot,status=$('#robotStatusCard'),position=r.position,mode=strategies[r.strategy]||strategies.intraday,busy=r.active||r.starting,boost=r.strategy==='boost',net=position?robotNet(position):0,locked=boost&&position&&net<-1e-8;$('#robotPair').textContent=displayPair();$('#robotScore').textContent=`${signal.score} / 100`;$('#robotSignal').textContent=position?(locked?'Recuperação 0×0':'Posição comprada'):r.starting?'Preparando dados':signal.label;$('#robotSessionProfit').textContent=`${r.sessionProfit>=0?'+':''}${fmt(r.sessionProfit)}`;$('#robotNavStatus').textContent=r.active?(boost?'BOOST':'ON'):r.starting?'...':'OFF';$('#robotNavStatus').classList.toggle('on',busy);status.className=`robot-status-card ${position?'position':r.active?'active':'off'} ${boost?'boost':''}`;$('#robotStatusLabel').textContent=locked?'TRAVA 0×0 ATIVA':position?'OPERAÇÃO EM ANDAMENTO':r.starting?'PREPARANDO O ROBÔ':r.active?'ROBÔ MONITORANDO':'ROBÔ DESATIVADO';$('#robotStatusText').textContent=locked?`Aguardando ${state.asset} recuperar ${formatPrice(position.breakEven)} sem realizar perda`:position?`Gerenciando ${displayPair()} até o alvo líquido`:r.starting?'Atualizando candles e indicadores':r.active?`${mode.label} procurando entrada válida`:'Configure a estratégia para iniciar';$('#startRobot').disabled=busy;$('#stopRobot').disabled=!r.active&&!position;$('#stopRobot').textContent=r.stopRequested&&position?'■ Saída pendente em 0×0':'■ Parar e encerrar';$('#robotStrategy').disabled=busy;$('#robotInvestment').disabled=busy;$('#robotMaxTrades').disabled=busy;
  const badge=$('.entry-badge');if(badge){badge.querySelector('small').textContent=signal.score>=signal.strategy.score?'ENTRADA PROVÁVEL':'SINAL EM ANÁLISE';badge.querySelector('strong').textContent=`${signal.score}% confiança`;badge.classList.toggle('robot-live',r.active)}
  const box=$('#robotPosition');box.hidden=!position;if(position){const goal=robotGoalProgress(position),progress=Math.round(goal.progress),remaining=Math.ceil(goal.remaining),positive=goal.progress>=50,track=$('#robotGoalTrack'),fill=$('#robotGoalFill');$('#robotPositionResult').textContent=`${net>=0?'+':''}${net.toFixed(2).replace('.',',')}%`;$('#robotPositionResult').className=net>=0?'positive':'negative';$('#robotEntry').textContent=formatPrice(position.entry);$('#robotTarget').textContent=formatPrice(position.target);$('#robotStop').textContent=boost?`0×0 · ${formatPrice(position.breakEven)}`:formatPrice(position.stop);$('#robotGoalPercent').textContent=`${progress}%`;$('#robotGoalPercent').className=positive?'positive':'negative';track.classList.toggle('negative',!positive);track.classList.toggle('boost-locked',!!locked);$('#robotGoalMarker').style.left=`${goal.progress}%`;fill.style.left=`${positive?50:goal.progress}%`;fill.style.width=`${Math.abs(goal.progress-50)}%`;const goalText=$('#robotGoalText');goalText.textContent=locked?`Sem saída negativa. Projeção recalculada para recuperar até ${formatPrice(position.breakEven)} (resultado 0×0).`:positive?remaining?`Faltam ${remaining}% do percurso para bater o alvo.`:'Alvo atingido — preparando a saída automática.':`Zona negativa: barra em ${progress}%, aproximando-se do stop; faltam ${remaining}% para o alvo.`;goalText.className=locked?'boost-lock':positive?'positive':'negative'}updateForecastLabel();renderRobotHistory()
}
async function startRobot(){
  const r=state.robot;if(r.active||r.starting)return;if(state.order.active){showToast('Operação em andamento','Encerre a operação atual antes de iniciar o robô.','exit');return}r.starting=true;r.strategy=$('#robotStrategy').value;renderRobotUI();try{r.investment=numberInRange(toBaseAmount($('#robotInvestment').value),500,10,1000000000);if(r.investment>availablePaperBalance())throw new Error(`Capital acima do saldo disponível de ${usdt(availablePaperBalance())}.`);r.maxTrades=Math.round(numberInRange($('#robotMaxTrades').value,3,1,20));const s=strategies[r.strategy]||strategies.intraday,costs=tradingCosts();if(costs.total*100>=s.risk)throw new Error('As taxas e o slippage precisam ser menores que o risco da estratégia.');r.trades=[];r.sessionProfit=0;r.position=null;r.stopRequested=false;r.lastActionAt=0;state.timeframe=s.entry;$('#profitTarget').value=s.target;$('#maxRisk').value=s.risk;$('#targetPercentLabel').textContent=`+${s.target.toFixed(2).replace('.',',')}%`;$$('#timeframes button').forEach(b=>b.classList.toggle('active',b.textContent===s.entry));$('#activeStrategy').textContent=`${s.label} · ${s.entry} / ${s.confirm} / ${s.trend}`;await loadMarketCandles();r.active=true;updateRobotRules();addNotification('Robô Trade iniciado',`${s.label} · capital ${usdt(r.investment)}.`);showToast(r.strategy==='boost'?'Boost ativado':'Robô Trade iniciado',`${s.label} monitorando ${displayPair()} em ${s.entry}.`)}catch(error){r.active=false;showToast('Não foi possível iniciar',error?.message||'Revise os dados e tente novamente.','exit')}finally{r.starting=false;renderRobotUI()}runRobot()
}
function openRobotPosition(signal){
  const r=state.robot;if(r.investment>availablePaperBalance()){r.active=false;showToast('Saldo insuficiente para nova entrada',`Disponível: ${usdt(availablePaperBalance())}. Reduza o capital por operação.`,'exit');renderRobotUI(signal);return}const s=strategies[r.strategy]||strategies.intraday,entry=state.currentPrice,fees=tradingCosts().total,target=entry*(1+fees+s.target/100),stop=entry*(1-Math.max(.001,s.risk/100-fees)),breakEven=entry*(1+fees),protection=r.strategy==='boost'?'breakeven':'technical';r.position={symbol:state.asset,marketSymbol:state.marketSymbol,owner:'robot',entry,target,stop,breakEven,protection,fees,investment:r.investment,strategy:s.label,score:signal.score,riskPercent:s.risk,openedAt:Date.now()};r.stopRequested=false;r.lastActionAt=Date.now();state.order={active:true,entry,target,stop,breakEven,protection,fees,investment:r.investment,owner:'robot',symbol:state.asset,strategy:s.label,score:signal.score,riskPercent:s.risk,openedAt:r.position.openedAt,marketSymbol:state.marketSymbol,targetPercent:s.target,trailing:false,peakPrice:entry,approachAlerted:false,targetAlerted:false};$('#entryPrice').textContent=formatPrice(entry);$('#targetPrice').textContent=formatPrice(target);$('#stopPrice').textContent=r.strategy==='boost'?`0×0 · ${formatPrice(breakEven)}`:formatPrice(stop);$('#targetPercentLabel').textContent=`+${s.target.toFixed(2).replace('.',',')}%`;$('.status-pill').textContent='● Robô em operação';$('#exitTradeBtn').disabled=false;$('#closeTradeBtn').disabled=false;addNotification('Entrada automática registrada',`${displayPair()} · ${s.label} · confiança ${signal.score}/100.`);showToast(r.strategy==='boost'?'Entrada Boost registrada':'Entrada automática registrada',`${displayPair()} · confiança ${signal.score}/100.`);updateOperation();renderRobotUI(signal);drawChart()
}
function closeRobotPosition(reason){
  const r=state.robot,p=r.position;if(!p)return false;const currentNet=robotNet(p);if(r.strategy==='boost'&&currentNet<-1e-8){r.stopRequested=r.stopRequested||/desativado|parar|manual/i.test(String(reason));showToast('Trava 0×0 ativa',`A saída ficou pendente até ${displayPair()} recuperar o resultado líquido para 0,00%.`,'exit');renderRobotUI();drawChart();return false}let record;try{record=settleTrade(p,state.currentPrice,reason)}catch(error){showToast('Falha ao encerrar',error.message,'exit');return false}r.trades.unshift(record);r.sessionProfit+=record.value;r.position=null;r.stopRequested=false;r.lastActionAt=Date.now();state.order.active=false;$('.status-pill').textContent='● Encerrada pelo robô';$('#exitTradeBtn').disabled=true;$('#closeTradeBtn').disabled=true;if(r.trades.length>=r.maxTrades)r.active=false;showToast(record.net>0?'Saída automática com lucro':'Saída automática protegida',`${reason} · ${record.net>=0?'+':''}${record.net.toFixed(2).replace('.',',')}% líquido.`,record.net>=0?'success':'exit');renderRobotUI();drawChart();return true
}
function runRobot(){const r=state.robot,signal=calculateRobotSignal(),s=signal.strategy;r.lastScore=signal.score;renderRobotUI(signal);if((!r.active&&!r.position)||state.marketChanging)return;if(r.position){const p=r.position,net=robotNet(p);if(r.strategy==='boost'){if(net>=s.target)closeRobotPosition('Lucro Boost de +0,20% atingido');else if(net>=-1e-8&&(r.stopRequested||signal.score<=s.reversal))closeRobotPosition(r.stopRequested?'Saída protegida solicitada pelo usuário':'Reversão encerrada em 0×0');else{updateForecastLabel();drawChart()}return}if(net>=s.target)closeRobotPosition('Meta da estratégia atingida');else if(state.currentPrice<=p.stop)closeRobotPosition('Stop de proteção atingido');else if(signal.score<=s.reversal)closeRobotPosition('Reversão do sinal detectada');return}if(!r.active)return;if(r.trades.length>=r.maxTrades){r.active=false;renderRobotUI(signal);showToast('Limite da sessão atingido',`${r.maxTrades} operações automáticas concluídas.`);return}if(Date.now()-r.lastActionAt<s.cooldown)return;if(signal.score>=s.score)openRobotPosition(signal)}
function stopRobot(){const r=state.robot,p=r.position;if(p&&r.strategy==='boost'&&robotNet(p)<-1e-8){r.stopRequested=true;r.active=true;showToast('Parada programada em 0×0',`O Boost não abrirá outra ordem e encerrará esta posição assim que não houver perda.`,'exit');renderRobotUI();return}const hadPosition=!!p;r.active=false;if(hadPosition)closeRobotPosition('Robô desativado pelo usuário');else{renderRobotUI();showToast('Robô Trade desativado','Nenhuma nova entrada será registrada.','exit')}}
function openTrade(){if(state.robot.active||state.robot.starting){showToast('Robô Trade ativo','Pause o robô antes de registrar uma entrada manual.','exit');return}if(state.order.active){showToast('Operação em andamento','Registre a saída antes de criar uma nova entrada.','exit');return}const balance=availablePaperBalance();if(balance<10){showToast('Saldo insuficiente','Reinicie a carteira com pelo menos 10 USD equivalentes para continuar.','exit');return}const investment=$('#investment'),displayBalance=fromBaseAmount(balance);investment.max=String(displayBalance);if(Number(investment.value)>displayBalance)investment.value=String(displayBalance.toFixed(2));calcTarget();const d=$('#tradeModal');if(typeof d.showModal==='function')d.showModal()}
function numberInRange(value,fallback,min,max){const number=Number(value);return Number.isFinite(number)?Math.min(max,Math.max(min,number)):fallback}
function tradingCosts(){const buy=numberInRange($('#buyFee').value,.1,0,20),sell=numberInRange($('#sellFee').value,.1,0,20),slippage=numberInRange($('#slippage').value,.05,0,20);return{buy,sell,slippage,total:(buy+sell+2*slippage)/100}}
function calcTarget(){const entry=state.currentPrice,costs=tradingCosts(),target=numberInRange($('#profitTarget').value,2,.01,100)/100,invest=numberInRange(toBaseAmount($('#investment').value),0,0,1000000000),price=entry*(1+costs.total+target);$('#modalTarget').textContent=formatPrice(price);$('#expectedProfit').textContent=fmt(invest*target);return price}
function showToast(title,text,kind='success'){const toast=$('#toast');toast.querySelector('span').textContent=kind==='exit'?'↘':'✓';toast.querySelector('strong').textContent=title;toast.querySelector('small').textContent=text;toast.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.classList.remove('show'),3000)}
function showGoalAlert(hit=false){const alert=$('#goalAlert');alert.classList.toggle('hit',hit);$('#goalAlertLabel').textContent=hit?'META ATINGIDA':'ALERTA DE PROXIMIDADE';$('#goalAlertTitle').textContent=hit?'Lucro líquido atingido':'Preço próximo ao alvo';$('#goalAlertText').textContent=hit?'A operação pode ser encerrada conforme o objetivo escolhido.':'Falta menos de 0,20% para o lucro definido na ordem.';addNotification(hit?'Meta líquida atingida':'Preço próximo ao alvo',`${displayPair()} · ${formatPrice(state.currentPrice)}.`);const old=alert.querySelector(':scope>i'),timer=old.cloneNode();old.replaceWith(timer);alert.classList.add('show');clearTimeout(showGoalAlert.timer);showGoalAlert.timer=setTimeout(()=>alert.classList.remove('show'),3000)}
function updateOperation(){
  if(!state.order.active)return;
  if(state.order.trailing){state.order.peakPrice=Math.max(Number(state.order.peakPrice)||state.currentPrice,state.currentPrice);const risk=Math.max(.1,Number(state.order.riskPercent)||1.5),distance=Math.max(.001,risk/100-state.order.fees),trailingStop=state.order.peakPrice*(1-distance);if(trailingStop>state.order.stop){state.order.stop=trailingStop;$('#stopPrice').textContent=formatPrice(trailingStop)}}
  if(state.order.owner==='manual'&&state.currentPrice<=state.order.stop){closeActiveOrder(state.order.trailing?'Trailing stop atingido':'Stop técnico atingido');return}
  const gross=(state.currentPrice/state.order.entry-1)*100,net=gross-state.order.fees*100,targetPct=Math.max(.01,Number(state.order.targetPercent)||numberInRange($('#profitTarget').value,2,.01,100)),remaining=Math.max(0,targetPct-net),progress=Math.max(0,Math.min(100,net/targetPct*100));
  $('#grossProfit').textContent=(gross>=0?'+':'')+gross.toFixed(2).replace('.',',')+'%';$('#grossProfit').className=gross>=0?'positive':'negative';$('#estimatedCosts').textContent=(state.order.fees*100).toFixed(2).replace('.',',')+'%';$('#netProfit').textContent=(net>=0?'+':'')+net.toFixed(2).replace('.',',')+'%';$('#netProfit').className=net>=0?'positive':'negative';$('#remainingProfit').textContent=remaining.toFixed(2).replace('.',',')+'%';$('#progressLabel').textContent=Math.round(progress)+'%';$('#goalProgress').style.width=progress+'%';$('#currentPin').style.left=progress+'%';
  const distance=(state.order.target-state.currentPrice)/state.order.target*100;if(distance<=.2&&distance>0&&!state.order.approachAlerted){state.order.approachAlerted=true;showGoalAlert(false)}if(state.currentPrice>=state.order.target&&!state.order.targetAlerted){state.order.targetAlerted=true;showGoalAlert(true)}
}
function selectStrategy(key){state.strategy=key;const s=strategies[key];$$('.strategy-card').forEach(c=>c.classList.toggle('active',c.dataset.strategy===key));$('#strategyScore').textContent=s.score+' / 100';$('#strategyRisk').textContent=s.risk.toFixed(1).replace('.',',')+'%';$('#strategyExposure').textContent=s.exposure}
function applyStrategy(){if(state.robot.active||state.robot.starting){$('#strategyModal').close();showToast('Robô Trade ativo','Pare o robô para trocar a estratégia principal.','exit');return}const s=strategies[state.strategy];$('#profitTarget').value=s.target;$('#maxRisk').value=s.risk;$('#targetPercentLabel').textContent='+'+s.target.toFixed(2).replace('.',',')+'%';state.timeframe=s.entry;$$('#timeframes button').forEach(b=>b.classList.toggle('active',b.textContent===s.entry));$('#activeStrategy').textContent=s.label+' · '+s.entry+' / '+s.confirm+' / '+s.trend;calcTarget();loadMarketCandles();$('#strategyModal').close();showToast('Estratégia aplicada',s.label+' ajustou gráfico, meta e risco.')}
function closeActiveOrder(reason='Saída manual registrada'){if(!state.order.active)return;if(state.order.owner==='robot'){closeRobotPosition(typeof reason==='string'?reason:'Saída manual registrada');return}let record;try{record=settleTrade(state.order,state.currentPrice,typeof reason==='string'?reason:'Saída manual registrada')}catch(error){showToast('Falha ao encerrar',error.message,'exit');return}state.order.active=false;state.order.trailing=false;$('.status-pill').textContent='● Encerrada';$('#exitTradeBtn').disabled=true;$('#closeTradeBtn').disabled=true;$('#trailingBtn').classList.remove('active');$('#trailingBtn').textContent='◇ Ativar trailing stop';showToast(record.net>=0?'Saída com lucro registrada':'Saída com perda registrada',`${record.net>=0?'+':''}${record.net.toFixed(2).replace('.',',')}% · ${signedUsdt(record.value)}.`,record.net>=0?'success':'exit');drawChart()}
function openRobotPage(){const page=$('#robotPage'),main=$('.main');if(page.parentElement!==main)main.append(page);main.classList.add('robot-view');page.hidden=false;document.body.classList.add('robot-page-open');document.documentElement.scrollTop=0;document.body.scrollTop=0;renderRobotUI()}
function closeRobotPage(updateNavigation=true){const page=$('#robotPage'),main=$('.main');page.hidden=true;main.classList.remove('robot-view');document.body.classList.remove('robot-page-open');if(updateNavigation){$$('.nav-item').forEach(item=>item.classList.toggle('active',item.dataset.view==='Visão geral'));setTimeout(drawChart,30)}}
function setupUI(){
  $$('#timeframes button').forEach(b=>b.onclick=async()=>{if(state.robot.active||state.robot.starting){showToast('Tempo controlado pelo robô',`A estratégia ${strategies[state.robot.strategy].label} utiliza ${strategies[state.robot.strategy].entry}.`,'exit');return}$$('#timeframes button').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.timeframe=b.textContent;await loadMarketCandles()});
  $('#projectionBtn').onclick=()=>{state.projection=!state.projection;$('#projectionBtn').classList.toggle('active',state.projection);$('.forecast-label').style.display=state.projection?'block':'none';drawChart()};
  $('#resetChart').onclick=()=>loadMarketCandles();
  $('#fullscreenBtn').onclick=()=>$('#chartWrap').requestFullscreen?.();
  $('#themeBtn').onclick=()=>{document.body.classList.toggle('light');state.theme=document.body.classList.contains('light')?'light':'dark';drawChart();configureGoogleSignIn()};
  $('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('open');
  $$('.nav-item').forEach(n=>n.onclick=()=>{$$('.nav-item').forEach(x=>x.classList.remove('active'));n.classList.add('active');if(n.dataset.view!=='Robô Trade')closeRobotPage(false);if(n.dataset.view==='Estratégias')$('#strategyModal').showModal();if(n.dataset.view==='Mercados'){if(typeof $('#marketsModal').showModal==='function')$('#marketsModal').showModal();loadMarkets()}if(n.dataset.view==='Robô Trade')openRobotPage();openFinanceView(n.dataset.view);if(innerWidth<980)$('#sidebar').classList.remove('open')});
  $('#simulateBtn').onclick=openTrade;
  $$('#tradeForm input').forEach(i=>i.addEventListener('input',calcTarget));
  $('#confirmTrade').onclick=e=>{e.preventDefault();if(state.order.active){$('#tradeModal').close();showToast('Operação em andamento','Registre a saída antes de criar uma nova entrada.','exit');return}const target=calcTarget(),entry=state.currentPrice,investment=numberInRange(toBaseAmount($('#investment').value),0,10,1000000000),targetPercent=numberInRange($('#profitTarget').value,2,.01,100),risk=numberInRange($('#maxRisk').value,1.5,.1,100),fees=tradingCosts().total;if(investment>availablePaperBalance()){showToast('Saldo insuficiente',`Disponível na carteira: ${usdt(availablePaperBalance())}.`,'exit');return}if(fees*100>=risk){showToast('Custos acima do risco','Reduza taxas/slippage ou aumente o risco máximo.','exit');return}const stop=entry*(1-Math.max(.001,risk/100-fees)),strategy=strategies[state.strategy]?.label||'Manual',score=calculateRobotSignal().score,openedAt=Date.now();state.order={active:true,entry,target,stop,fees,investment,owner:'manual',symbol:state.asset,strategy,score,riskPercent:risk,openedAt,marketSymbol:state.marketSymbol,targetPercent,trailing:false,peakPrice:entry,approachAlerted:false,targetAlerted:false};$('#entryPrice').textContent=formatPrice(entry);$('#targetPrice').textContent=formatPrice(target);$('#stopPrice').textContent=formatPrice(stop);$('#targetPercentLabel').textContent='+'+targetPercent.toFixed(2).replace('.',',')+'%';$('#tradeModal').close();$('.status-pill').textContent='● Em andamento';$('#exitTradeBtn').disabled=false;$('#closeTradeBtn').disabled=false;addNotification('Entrada manual registrada',`${displayPair()} · ${strategy} · capital ${usdt(investment)}.`);showToast('Operação simulada criada','Agora acompanhamos sua meta líquida.');updateOperation();drawChart()};
  $$('.strategy-card').forEach(c=>c.onclick=()=>selectStrategy(c.dataset.strategy));$('#applyStrategy').onclick=e=>{e.preventDefault();applyStrategy()};
  $('#closeMarkets').onclick=()=>$('#marketsModal').close();$('#refreshMarkets').onclick=()=>loadMarkets(true);
  $('#closeRobot').onclick=()=>closeRobotPage(true);$('#startRobot').onclick=startRobot;$('#stopRobot').onclick=stopRobot;$('#robotStrategy').onchange=()=>{state.robot.strategy=$('#robotStrategy').value;if(state.robot.strategy==='boost'&&Number($('#robotMaxTrades').value)<=3)$('#robotMaxTrades').value=strategies.boost.suggestedTrades;updateRobotRules();renderRobotUI()};
  $('#exitTradeBtn').disabled=true;$('#closeTradeBtn').disabled=true;$('#exitTradeBtn').onclick=()=>closeActiveOrder();$('#closeTradeBtn').onclick=()=>closeActiveOrder();
  $('#trailingBtn').onclick=()=>{if(!state.order.active){showToast('Nenhuma operação ativa','Abra uma operação antes de configurar o trailing stop.','exit');return}if(state.order.owner==='robot'){showToast('Gestão automática ativa','O robô já controla alvo, stop e reversão desta posição.','exit');return}state.order.trailing=!state.order.trailing;state.order.peakPrice=state.currentPrice;$('#trailingBtn').classList.toggle('active',state.order.trailing);$('#trailingBtn').textContent=state.order.trailing?'✓ Trailing stop ativo':'◇ Ativar trailing stop';addNotification(state.order.trailing?'Trailing stop ativado':'Trailing stop desativado',`${displayPair()} · stop atual ${formatPrice(state.order.stop)}.`);updateOperation()};
  window.addEventListener('resize',drawChart); document.addEventListener('fullscreenchange',()=>setTimeout(drawChart,50));
}
async function tick(){if(state.marketChanging)return;if(state.dataSource==='binance'){const refreshMs=state.robot.active&&state.robot.strategy==='boost'?4000:10000;if(state.liveRefreshing||Date.now()-state.lastLiveRefresh<refreshMs)return;state.liveRefreshing=true;state.lastLiveRefresh=Date.now();try{const quote=await fetchBinance(`/api/v3/ticker/price?symbol=${encodeURIComponent(state.marketSymbol)}`),price=Number(quote.price);if(!Number.isFinite(price)||price<=0)throw new Error('Preço inválido');state.liveFailures=0;state.currentPrice=price;candles.at(-1).close=price;candles.at(-1).high=Math.max(candles.at(-1).high,price);candles.at(-1).low=Math.min(candles.at(-1).low,price);$('#currentPrice').textContent=formatPrice(price);evaluatePriceAlerts();updateOperation();runRobot();drawChart()}catch(error){state.liveFailures+=1;runRobot();if(state.liveFailures>=3){state.dataSource='simulated';$('#statSource').textContent='Fallback local';showToast('Conexão instável','O preço continuará no modo simulado até selecionar o mercado novamente.','exit')}}finally{state.liveRefreshing=false}return}const pulse=(Math.random()-.46)*Math.max(state.currentPrice*.00018,.000001);state.currentPrice+=pulse;candles.at(-1).close=state.currentPrice;candles.at(-1).high=Math.max(candles.at(-1).high,state.currentPrice);candles.at(-1).low=Math.min(candles.at(-1).low,state.currentPrice);$('#currentPrice').textContent=formatPrice(state.currentPrice);evaluatePriceAlerts();updateOperation();runRobot();drawChart()}
restoreAppSettings();initializeFinance();$('#investment').value=fromBaseAmount(500).toFixed(2);$('#robotInvestment').value=fromBaseAmount(500).toFixed(2);setupSearch();setupUI();setupSettingsUI();setupChartInteraction();applyCurrencyUI(null,false);calcTarget();drawChart();updateRobotRules();renderRobotUI();refreshFxRates(false);setInterval(tick,4200);
